INSERT ALL
    INTO POZWOLENIA VALUES (1, 'Admin', 1, 1, 1, 1, 1)
    INTO POZWOLENIA VALUES (2, 'Shadow_Admin', 0, 0, 0, 1, 1)
    INTO POZWOLENIA VALUES (3, 'User', 1, 1, 1, 0, 0)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO TYP_ZGLOSZENIA VALUES (1, 'Bug')
    INTO TYP_ZGLOSZENIA VALUES (2, 'Poprawka')
    INTO TYP_ZGLOSZENIA VALUES (3, 'Nowa funkcjonalność')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO PRIORITET VALUES (1, 'Niski')
    INTO PRIORITET VALUES (2, 'Średni')
    INTO PRIORITET VALUES (3, 'Wysoki')
    INTO PRIORITET VALUES (4, 'Krytyczny')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO UZYTKOWNIK VALUES (1, 'Patryk Dyndal', 'PDyndal', 'PDyndal@example.com', 1)
    INTO UZYTKOWNIK VALUES (2, 'Ewa Janisz', 'EJanisz', 'EJanisz@example.com', 0)
    INTO UZYTKOWNIK VALUES (3, 'Example User', 'User', 'User@example.com', 1)
    INTO UZYTKOWNIK VALUES (4, 'Shadow Admin', 'Shadow', 'Shadow@example.com', 1)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO ROLE VALUES (1, 1)
    INTO ROLE VALUES (2, 1)
    INTO ROLE VALUES (3, 3)
    INTO ROLE VALUES (4, 2)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO PROJEKT VALUES (1, 'TEST', CURRENT_TIMESTAMP)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO ZARZADZANIE_PROJEKTEM VALUES (1, 1)
    INTO ZARZADZANIE_PROJEKTEM VALUES (1, 2)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO UTWORZONE VALUES (1, 1, CURRENT_TIMESTAMP)
SELECT 1 FROM DUAL;

INSERT ALL	
    INTO ZGLOSZENIA VALUES (1, 'Testowe zgloszenie', 'LOREM Ipsum Dolor Sit Amet', 1, 1, 1, null, 'Brak', 1 )
SELECT 1 FROM DUAL;