INSERT ALL
    INTO POZWOLENIA ( NAZWA, CREATE_ISSUE, EDIT_OWN_ISSUE, DELETE_OWN_ISSUE, EDIT_ANY_ISSUE, DELETE_ANY_ISSUE ) VALUES ('Admin', 1, 1, 1, 1, 1)
    INTO POZWOLENIA ( NAZWA, CREATE_ISSUE, EDIT_OWN_ISSUE, DELETE_OWN_ISSUE, EDIT_ANY_ISSUE, DELETE_ANY_ISSUE ) VALUES ('Shadow_Admin', 0, 0, 0, 1, 1)
    INTO POZWOLENIA ( NAZWA, CREATE_ISSUE, EDIT_OWN_ISSUE, DELETE_OWN_ISSUE, EDIT_ANY_ISSUE, DELETE_ANY_ISSUE ) VALUES ('User', 1, 1, 1, 0, 0)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO TYP_ZGLOSZENIA( NAZWA ) VALUES ('Bug')
    INTO TYP_ZGLOSZENIA( NAZWA ) VALUES ('Poprawka')
    INTO TYP_ZGLOSZENIA( NAZWA ) VALUES ('Nowa funkcjonalność')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO PRIORITET( TYP ) VALUES ('Niski')
    INTO PRIORITET( TYP ) VALUES ('Średni')
    INTO PRIORITET( TYP ) VALUES ('Wysoki')
    INTO PRIORITET( TYP ) VALUES ('Krytyczny')
SELECT 1 FROM DUAL;

INSERT ALL
    INTO UZYTKOWNIK( IMIE_NAZWISKO, NAZWA_WYSWIETLANA, EMAIL, ZEZWOL_NA_POWIADOMIENIA_EMAIL ) VALUES ('Patryk Dyndal', 'PDyndal', 'PDyndal@example.com', 1)
    INTO UZYTKOWNIK( IMIE_NAZWISKO, NAZWA_WYSWIETLANA, EMAIL, ZEZWOL_NA_POWIADOMIENIA_EMAIL ) VALUES ('Ewa Janisz', 'EJanisz', 'EJanisz@example.com', 0)
    INTO UZYTKOWNIK( IMIE_NAZWISKO, NAZWA_WYSWIETLANA, EMAIL, ZEZWOL_NA_POWIADOMIENIA_EMAIL ) VALUES ('Example User', 'User', 'User@example.com', 1)
    INTO UZYTKOWNIK( IMIE_NAZWISKO, NAZWA_WYSWIETLANA, EMAIL, ZEZWOL_NA_POWIADOMIENIA_EMAIL ) VALUES ('Shadow Admin', 'Shadow', 'Shadow@example.com', 1)
SELECT 1 FROM DUAL;

INSERT ALL
    INTO PROJEKT( OPIS, CZAS_MODYFIKACJI ) VALUES ('TEST', CURRENT_TIMESTAMP)
SELECT 1 FROM DUAL;
